{{- if .Values.canary.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: helm-canary-canary-svc
spec:
  type: NodePort
  ports:
  - port: 3000
    protocol: TCP
  selector:
    app: helm-canary-canary-app
{{- end }}
