{{- if .Values.canary.enabled }}
apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name: helm-canary-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "{{ .Values.canary.trafficPct }}"
spec:
  rules:
  - host: helm-canary.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: helm-canary-canary-svc
          servicePort: 3000
{{- end }}